### ISSUE TITLE
undefined: http.NewRequestWithContext

### ISSUE THREAD

**Issue by vasth** [ysmood/kit#1]
0003 Failed to build the application: # github.com/ysmood/kit/pkg/http
..\..\..\..\github.com\ysmood\kit\pkg\http\req.go:220:14: undefined: http.NewRequestWithContext

**Comment by ysmood** [comment]
@vasth your golang version is below v1.13, please update your golang and try again.

See their doc https://golang.org/pkg/net/http/#NewRequestWithContext

Look at the red circle:

<img width="1259" alt="Screen Shot 2020-04-15 at 19 17 05" src="https://user-images.githubusercontent.com/1415488/79326448-d28eba80-7f4d-11ea-92ff-c6e876a71706.png">
